### ISSUE TITLE
broker配置问题

### ISSUE THREAD

**Issue by xinmans** [xdusongwei/HODL#6]
apple $225.00(-1.41%)
[US]AAPLEDT: 2024-11-15T16:00:00
市场:富途证券 行情:富途证券 交易:长桥证券

quote: Quote(symbol='AAPL', open=226.4, pre_close=228.22, latest_price=225.0, time=datetime.datetime(2024, 11, 15, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='US/Eastern')), status='NORMAL', day_low=224.27, day_high=226.92, broker_name='futu', broker_display='富途证券')
quote: Quote(symbol='AAPL', open=226.4, pre_close=228.22, latest_price=225.0, time=datetime.datetime(2024, 11, 15, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='US/Eastern')), status='NORMAL', day_low=224.27, day_high=226.92, broker_name='futu', broker_display='富途证券')
quote: Quote(symbol='AAPL', open=226.4, pre_close=228.22, latest_price=225.0, time=datetime.datetime(2024, 11, 15, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='US/Eastern')), status='NORMAL', day_low=224.27, day_high=226.92, broker_name='futu', broker_display='富途证券')
quote: Quote(symbol='AAPL', open=226.4, pre_close=228.22, latest_price=225.0, time=datetime.datetime(2024, 11, 15, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='US/Eastern')), status='NORMAL', day_low=224.27, day_high=226.92, broker_name='futu', broker_display='富途证券')

配置里已经改成了longport，但是现实市场/行情都是富途，交易是长桥

如何设置成市场/行情/交易都是长桥？
[store.AAPL_longport]
region = "US"
currency = "USD"
broker = "longport"
symbol = "AAPL"
trade_strategy = "hodl"
trade_type = "stock"
name = "apple"
enable = true
visible = true
max_shares = 12345
state_file_path = "./state-{broker}-{symbol}-stage{stage}.json"
state_archive_folder = "./hodl/archive-{broker}-{symbol}"
buy_spread_rate = 0.0
sell_spread_rate = 0.004
buy_order_rate = 0.002
sell_order_rate = 0.002
precision = 2
shares_per_unit = 1
booting_check = true
base_price_last_buy = true
base_price_last_buy_days = 21
base_price_day_low = true
base_price_tumble_protect = true
base_price_using_broker = true
tumble_protect_day_range = 7
tumble_protect_rsi = true
tumble_protect_rsi_unlock_limit = 75
tumble_protect_rsi_warning_limit = 25
lock_position = true
price_rate = 1.0
rework_level = 1
market_price_rate = 0.005
sleep_mode = true

**Comment by xdusongwei** [comment]
如果你配置了多个券商通道, 那么系统随机产生一组获取顺序去拿市场行情数据,
如果你一定要不去用某一家数据, 要么把券商通道的配置去掉, 要么把不想用的券商的 [broker_meta](https://github.com/xdusongwei/HODL/blob/master/hodl/tools/broker_meta.py#L11) 功能范围限制掉
如果只是想优先用一种获取信息的顺序, 可以考虑这 [两项](https://github.com/xdusongwei/HODL/blob/master/hodl/tools/variable.py#L219)设置
